branches:
  only: 
    - master
language: csharp
solution: sdk/DocuSign.eSign.sln
mono: none
sudo: required
dist: trusty
dotnet: latest

services:
  - docker

install:
  - dotnet restore ./sdk/src/DocuSign.eSign/DocuSign.eSign.csproj
  - dotnet build --framework netstandard2.0 ./sdk/src/DocuSign.eSign/DocuSign.eSign.csproj