branches:
  only: 
    - master
language: csharp
solution: sdk/DocuSign.eSign.sln
mono: none
sudo: required
dist: trusty
dotnet: 2.1.2

services:
  - docker

install:
  - dotnet restore ./sdk/src/DocuSign.eSign/DocuSign.eSign.csproj
  - dotnet build ./sdk/src/DocuSign.eSign/DocuSign.eSign.csproj