branches:
  only: 
    - master
language: csharp
solution: sdk/DocuSign.eSign.sln
mono: none
sudo: required
dist: trusty
dotnet: 1.1.5

script:
    - dotnet build ./sdk/src/DocuSign.eSign/DocuSign.eSign.csproj --verbosity m