version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
build_script:
- ps: . ./csharp-build.ps1
test_script:
- ps: >- 
    dotnet build --framework net45 ./test/SdkTests/SdkTests.csproj

    dotnet build --framework netcoreapp2.0 ./test/SdkNetCoreTests/SdkNetCoreTests.csproj

    dotnet test ./test/SdkTests/bin/Debug/SdkTests.dll --verbosity d

    dotnet test ./test/SdkNetCoreTests/bin/Debug/netcoreapp2.0/SdkNetCoreTests.dll --verbosity diag